export const TID = {
  nav: {
    overview: "nav-overview",
    reviews: "nav-reviews",
    simulator: "nav-simulator",
    analytics: "nav-analytics",
    policies: "nav-policies",
    settings: "nav-settings",
  },
  overview: {
    root: "overview-page",
    kpiRuns: "kpi-total-runs",
    kpiFindings: "kpi-total-findings",
    kpiCritical: "kpi-critical",
    kpiCost: "kpi-cost",
    kpiLatency: "kpi-latency",
    feed: "overview-recent-feed",
    health: "overview-health-strip",
    topology: "overview-graph-topology",
  },
  reviews: {
    root: "reviews-page",
    table: "reviews-table",
    row: (id) => `review-row-${id}`,
    filter: (s) => `reviews-filter-${s}`,
    refresh: "reviews-refresh-btn",
  },
  detail: {
    root: "review-detail-page",
    back: "review-detail-back",
    status: "review-detail-status",
    risk: "review-detail-risk",
    trace: "review-trace-timeline",
    node: (n) => `trace-node-${n}`,
    findings: "review-findings-list",
    finding: (i) => `finding-card-${i}`,
    tools: "review-tool-violations",
    policies: "review-retrieved-policies",
    metrics: "review-metrics",
    publish: "review-publish-btn",
    delete: "review-delete-btn",
    tab: (t) => `review-tab-${t}`,
  },
  sim: {
    root: "simulator-page",
    sample: (id) => `sim-sample-${id}`,
    repo: "sim-repo-input",
    path: "sim-path-input",
    code: "sim-code-textarea",
    run: "sim-run-btn",
    ghOwner: "gh-owner-input",
    ghRepo: "gh-repo-input",
    ghNumber: "gh-number-input",
    ghPublish: "gh-publish-switch",
    ghRun: "gh-run-btn",
  },
  analytics: {
    root: "analytics-page",
    severity: "analytics-severity-chart",
    timeline: "analytics-timeline-chart",
    cwe: "analytics-cwe-chart",
    tools: "analytics-tools-chart",
    cost: "analytics-cost-panel",
    resilience: "analytics-resilience-panel",
  },
  policies: {
    root: "policies-page",
    list: "policies-list",
    item: (id) => `policy-item-${id}`,
    addTitle: "policy-title-input",
    addCategory: "policy-category-input",
    addCwe: "policy-cwe-input",
    addContent: "policy-content-textarea",
    addBtn: "policy-add-btn",
    searchInput: "policy-search-input",
    searchBtn: "policy-search-btn",
    searchResults: "policy-search-results",
    delete: (id) => `policy-delete-${id}`,
    seed: "policy-seed-btn",
  },
  settings: {
    root: "settings-page",
    health: "settings-health",
    webhookUrl: "settings-webhook-url",
    copyWebhook: "settings-copy-webhook",
    sql: "settings-supabase-sql",
    copySql: "settings-copy-sql",
    refresh: "settings-refresh-btn",
  },
};
